% \VignetteIndexEntry{An introduction to GOSemSim}
% \VignetteEngine{knitr::knitr}
% \VignettePackage{GOSemSim}

% To compile this document, run the commands within R
% R CMD Sweave --engine=knitr::knitr --pdf GOSemSim.Rnw

\documentclass[12pt]{article}

<<knitr, echo=FALSE, results="hide">>=
library("knitr")
opts_chunk$set(tidy         = FALSE, 
               out.truncate = 80,
               out.lines    = 6,
               dev          = 'pdf',
               include      = TRUE,
               fig.width    = 6,
               fig.height   = 6,
               resolution   = 100,
               message      = FALSE)
@

<<style-Sweave, eval=TRUE, echo=FALSE, results="asis">>=
BiocStyle::latex()
@ 

<<loadPKG, echo=FALSE>>=
library(org.Hs.eg.db)
library(GO.db)
library(GOSemSim)
@ 


\author{Guangchuang Yu \\[1em]
  \small{School of Public Health} \\
  \small{The University of Hong Kong} \\
  \small{\email{guangchuangyu@gmail.com}}
}

\title{GO-terms Semantic Similarity Measures}

\begin{document}

\maketitle

\begin{center}
  
  \vspace{1em}
  \textbf{\Biocpkg{GOSemSim} version:} \Sexpr{packageVersion("GOSemSim")}
  \vspace{1em}
  
  \begin{tabular}{ | l | }
    \hline
    If you use \Biocpkg{GOSemSim} in published research, please cite: \\
    \\
    G Yu, F Li, Y Qin, X Bo, Y Wu, S Wang. \textbf{GOSemSim: an R package for} \\
    \textbf{measuring semantic similarity among GO terms and gene products}. \\
    \emph{Bioinformatics} 2010, 26(7):976-978. \\
    \url{http://dx.doi.org/10.1093/bioinformatics/btq064} \\
    \hline
  \end{tabular}
  
\end{center}


<<options,results='hide',echo=FALSE>>=
options(digits=3, width=80, prompt=" ", continue=" ")
@

\newpage
\tableofcontents
\newpage

\section{Introduction}

Functional similarity of gene products can be estimated by controlled
biological vocabularies, such as Gene Ontology (GO). GO comprises of
three orthogonal ontologies, i.e. molecular function (MF), biological
process (BP), and cellular component (CC).
\\

Four methods have been presented to determine the semantic similarity
of two GO terms based on the annotation statistics of their common
ancestor terms (Resnik  \cite{philip_semantic_1999}, Jiang  \cite{jiang_semantic_1997},
Lin  \cite{lin_information-theoretic_1998} and Schlicker  \cite{schlicker_new_2006}).
Wang  \cite{wang_new_2007} proposed a
new method to measure the similarity based on the graph structure of
GO. Each of these methods has its own advantages and
weaknesses. \Biocpkg{GOSemSim} package  \cite{yu2010} is developed to compute
semantic similarity among GO terms, sets of GO terms, gene products,
and gene clusters, providing both five methods mentioned above. I have
developed another package, \Biocpkg{DOSE} \cite{yu_dose_2015}, for measuring semantic
similarity among DO terms and gene products at disease perspective.
\\

To start with \Biocpkg{GOSemSim} package, type following code below:

<<loading, eval=FALSE, results='hide'>>=
library(GOSemSim)
help(GOSemSim)
@


\section{Semantic Similarity Measurement Based on GO}

\subsection{Information content-based methods}
Four methods proposed by Resnik  \cite{philip_semantic_1999},
Jiang  \cite{jiang_semantic_1997}, Lin  \cite{lin_information-theoretic_1998}
and Schlicker  \cite{schlicker_new_2006} are information content (IC) based, which
depend on the frequencies of two GO terms involved and that of their
closest common ancestor term in a specific corpus of GO
annotations. The information content of a GO term is computed by the
negative log probability of the term occurring in GO corpus. A rarely used term contains a
greater amount of information.

The frequency of a term t is defined as:
$$ 
p(t) = \frac{n_{t'}}{N} 
	| t' \in \left\{t, \; children\: of\: t \right\}
$$
where $n_{t'}$ is the number of term t', and N is the total number of terms in GO corpus.

Thus the information content is defined as:
$$ IC(t) = -\log(p(t)) $$

As GO allow multiple parents for each concept, two terms can share
parents by multiple paths. IC-based methods calculate similarity of two GO terms based on the information content of their closest common ancestor term, which was also called most informative information ancestor (MICA).

\subsubsection{Resnik method}
The Resnik method is defined as:
$$
sim_{Resnik}(t_1,t_2) = IC(MICA)
$$

\subsubsection{Lin method}
The Lin method is defined as:
$$
sim_{Lin}(t_1,t_2) = \frac{2IC(MICA)}{IC(t_1)+IC(t_2)}
$$

\subsubsection{Rel method}
The Relevance method, which was proposed by Schlicker, combine Resnik's and Lin's method 
and is defined as:
$$
sim_{Rel}(t_1,t_2) = \frac{2IC(MICA)(1-p(MICA))}{IC(t_1)+IC(t_2)}
$$

\subsubsection{Jiang method}
The Jiang and Conrath's method is defined as:
$$
sim_{Jiang}(t_1,t_2) = 1-\min(1, IC(t_1) + IC(t_2) - 2IC(MICA))
$$


At present, \Biocpkg{GOSemSim} supports analysis
on many species. We used the following Bioconductor packages to
calculate the information content.

\begin{itemize}
  \item \Biocannopkg{org.At.tair.db}    for \textit{Arabidopsis}
  \item \Biocannopkg{org.Ag.eg.db}      for \textit{Anopheles}
  \item \Biocannopkg{org.Bt.eg.db}      for \textit{Bovine}
  \item \Biocannopkg{org.Cf.eg.db}      for \textit{Canine}
  \item \Biocannopkg{org.Gg.eg.db}      for \textit{Chicken}
  \item \Biocannopkg{org.Pt.eg.db}      for \textit{Chimp}
  \item \Biocannopkg{org.Sco.eg.db}     for \textit{Coelicolor}
  \item \Biocannopkg{org.EcK12.eg.db}   for \textit{E coli strain K12}
  \item \Biocannopkg{org.EcSakai.eg.db} for \textit{E coli strain Sakai}
  \item \Biocannopkg{org.Dm.eg.db}      for \textit{Fly}
  \item \Biocannopkg{org.Hs.eg.db}      for \textit{Human}
  \item \Biocannopkg{org.Pf.plasmo.db}  for \textit{Malaria}
  \item \Biocannopkg{org.Mm.eg.db}      for \textit{Mouse}
  \item \Biocannopkg{org.Ss.eg.db}      for \textit{Pig}
  \item \Biocannopkg{org.Rn.eg.db}      for \textit{Rat}
  \item \Biocannopkg{org.Mmu.eg.db}     for \textit{Rhesus}
  \item \Biocannopkg{org.Ce.eg.db}      for \textit{Worm}
  \item \Biocannopkg{org.Xl.eg.db}      for \textit{Xenopus}
  \item \Biocannopkg{org.Sc.sgd.db}     for \textit{Yeast}
  \item \Biocannopkg{org.Dr.eg.db}      for \textit{Zebrafish}
\end{itemize}

The information content will update regularly.

\subsection{Graph-based method}
Graph-based methods using the topology of GO graph structure to
compute semantic similarity. Formally, a GO term A can be represented
as $DAG_{A}=(A,T_{A},E_{A})$ where $T_{A}$ is the set of GO terms in
$DAG_{A}$, including term A and all of its ancestor terms in the GO
graph, and $E_{A}$ is the set of edges connecting the GO terms in
$DAG_{A}$.

\subsubsection{Wang method}
To encode the semantic of a GO term in a measurable format to enable a quantitative comparison, Wang firstly defined the semantic value of term A as the aggregate contribution of all terms in $DAG_{A}$ to the semantics of term A, terms closer to term A in $DAG_{A}$ contribute more to its semantics. Thus, defined the contribution of a GO term \textit{t} to the semantic of GO term A as the S-value of GO term \textit{t} related to term A. For any of term \textit{t} in $DAG_{A}$, its S-value related to term A, $S_{A}(\textit{t})$ is defined as:
$$
      \left\{
        \begin{array}{l}
          S_{A}(A)=1 \\
          S_{A}(\textit{t})=\max\{w_{e} \times S_{A}(\textit{t}') | \textit{t}' \in children \: of(\textit{t}) \} \; if \: \textit{t} \ne A
        \end{array}
      \right.
$$
where $w_{e}$ is the semantic contribution factor for edge $e \in
    E_{A}$ linking term \textit{t} with its child term
    \textit{t}'. Term A contributes to its own is defined as
    one. After obtaining the S-values for all terms in $DAG_{A}$, the
    semantic value of DO term A, SV(A), is calculated as:
$$
SV(A)=\displaystyle\sum_{t \in T_{A}} S_{A}(t)
$$
Thus given two GO terms A and B, the semantic similarity between these
    two terms is defined as:
$$
sim_{Wang}(A, B) = \frac{\displaystyle\sum_{t \in T_{A} \cap T_{B}}{S_{A}(t) + S_{B}(t)}}
						{SV(A) + SV(B)}
$$
    where $S_{A}(\textit{t})$ is the S-value of GO term \textit{t}
    related to term A and $S_{B}(\textit{t})$ is the S-value of GO
    term \textit{t} related to term B.

This method proposed by Wang \cite{wang_new_2007} determines the semantic
similarity of two GO terms based on both the locations of these terms
in the GO graph and their relations with their ancestor terms.

\subsection{goSim and mgoSim function}
In \Biocpkg{GOSemSim}, we implemented all these IC-based and graph-based methods. \Rfunction{goSim} calculate semantic similarity between two GO terms, while \Rfunction{mgoSim}  calculate semantic similarity between two sets of GO terms.

<<mgoSim>>=
goSim("GO:0004022", "GO:0005515", ont="MF", measure="Wang")
go1 = c("GO:0004022","GO:0004024","GO:0004174")
go2 = c("GO:0009055","GO:0005515")
mgoSim(go1, go2, ont="MF", measure="Wang", combine=NULL)
mgoSim(go1, go2, ont="MF", measure="Wang", combine="BMA")
@

\section{Gene Semantic Similarity Measurement}
On the basis of semantic similarity between GO terms, \Biocpkg{GOSemSim} can
also compute semantic similarity among sets of GO terms, gene
products, and gene clusters.


We implemented four methods which called \textit{max},
\textit{avg}, \textit{rcmax}, and \textit{BMA} to combine
semantic similarity scores of multiple GO terms. The similarities
among gene products and gene clusters which annotated by multiple GO
terms were also calculated by the same combine methods mentioned
above.

Suppose we have gene $g_1$ annotated by GO terms sets $GO_{1}=\{go_{11},go_{12} \cdots go_{1m}\}$
and $g_2$ annotated by $GO_{2}=\{go_{21},go_{22} \cdots go_{2n}\}$, \Biocpkg{GOSemSim} implemented four methods which called \Rfunction{max}, \Rfunction{avg}, \Rfunction{rcmax} and \Rfunction{BMA} to combine semantic similairty scores of multiple GO terms. 

\subsection{Combine methods}
\subsubsection{max}

The \Rfunction{max} method calculates the maximum semantic similarity score over all pairs of GO terms between these two GO term sets.
$$
sim_{max}(g\_1, g\_2) = \displaystyle\max_{1 \le i \le m, 1 \le j \le n} sim(go_{1i}, go_{2j})
$$

\subsubsection{avg}
The \Rfunction{avg} calculates the average semantic similarity score over all pairs of GO terms.
$$
sim_{avg}(g_1, g_2) = \frac{\displaystyle\sum_{i=1}^m\sum_{j=1}^nsim(go_{1i}, go_{2j})}
						{m \times n}
$$

\subsubsection{rcmax}
Similarities among two sets of GO terms form a matrix, the \Rfunction{rcmax} method uses the maximum of RowScore and ColumnScore as the similarity, where RowScore (or ColumnScore) is the average of maximum similarity on each row (or column).
$$
sim_{rcmax}(g_1, g_2) = \max(\frac{\displaystyle\sum_{i=1}^m \max_{1
    \le j \le n} sim(go_{1i}, go_{2j})}{m},
\frac{\displaystyle\sum_{j=1}^n \max_{1 \le i \le m} sim(go_{1i},
  go_{2j})}{n})
$$

\subsubsection{BMA}
The \Rfunction{BMA} method, used the best-match average strategy, calculates the average of all maximum similarities on each row and column, and is defined as:
$$
sim_{BMA}(g_1, g_2) = \frac{\displaystyle\sum_{1=i}^m \max_{1 \le j
    \le n}sim(go_{1i}, go_{2j}) + \displaystyle\sum_{1=j}^n \max_{1
    \le i \le m}sim(go_{1i}, go_{2j})} {m+n}
$$

\subsection{geneSim and mgeneSim}
In \Biocpkg{GOSemSim}, we implemented \Rfunction{geneSim} to calculate semantic similarity between two gene products, and \Rfunction{mgeneSim} to calculate semantic similarity among multiple gene products.
<<mgeneSim>>=
geneSim("241", "251", ont="MF", organism="human", measure="Wang", combine="BMA")
mgeneSim(genes=c("835", "5261","241", "994"), 
			ont="MF", organism="human", measure="Wang", 
			verbose=FALSE)
@

\subsection{clusterSim and mclusterSim}
We also implemented \Rfunction{clusterSim} for calculating semantic similarity between two gene clusters, and \Rfunction{mclusterSim} for calculating semantic similarities among multiple gene clusters.

<<clusterSim, eval=FALSE>>=
gs1 <- c("835", "5261","241", "994", "514", "533")
gs2 <- c("578","582", "400", "409", "411")
clusterSim(gs1, gs2, ont="MF", organism="human", measure="Wang", combine="BMA")

x <- org.Hs.egGO
hsEG <- mappedkeys(x)
set.seed <- 123
clusters <- list(a=sample(hsEG, 20), b=sample(hsEG, 20), c=sample(hsEG, 20))
mclusterSim(clusters, ont="MF", organism="human", measure="Wang", combine="BMA")
@

\section{Case Study}

We proposed a method for measuring functional
similarity of microRNAs \cite{yu_new_2011}. This method was based on semantic similarity
of microRNAs' target genes, and was calculated by \Biocpkg{GOSemSim}. We
further analyzed viral microRNAs using this method and compared significant KEGG pathways regulated by different viruses' microRNAs \cite{yu2011} using \Biocpkg{clusterProfiler}  \cite{yu2012}.


\section{GO enrichment analysis}

GO enrichment analysis can be supported by our package \Biocpkg{clusterProfiler} \cite{yu2012}, which supports hypergeometric test and Gene Set Enrichment Analysis (GSEA). Enrichment results across different gene clusters can be compared using \Rfunction{compareCluster} function.

\section{Disease Ontology Semantic and Enrichment analysis}

Disease Ontology (DO) annotates human genes in the context of disease. DO is important annotation in translating molecular findings from high-throughput data to clinical relevance. \Biocpkg{DOSE} \cite{yu_dose_2015} supports semantic similarity computation among DO terms and genes. Enrichment analysis including hypergeometric model and GSEA are also implemented to support discovering disease associations of high-throughput biological data.


\section{External documents}

\begin{itemize}
  \item \href{http://ygc.name/2014/11/23/proper-use-of-gosemsim/}{proper use of GOSemSim}
\end{itemize}

\section{Session Information}


\section{Session Information}

Here is the output of \Rcode{sessionInfo()} on the system on which this document was compiled:

<<sessInfo, results='asis', echo=FALSE>>=
toLatex(sessionInfo())
@


\bibliography{GOSemSim}
\end{document}

