library(GOSemSim)

context("IC based methods")

## `infoContentMethod_cpp()` is compiled code, and the wrapper generated by
## Rcpp::compileAttributes() instantiates `Rcpp::RNGScope`. That resolves
## `enterRNGScope` through `R_GetCCallable("Rcpp", ...)`, which only succeeds
## once the Rcpp namespace -- and therefore its shared library -- has been
## loaded. Importing a single symbol from Rcpp in NAMESPACE is what makes that
## happen. Without it every call below fails with
##
##     function 'enterRNGScope' not provided by package 'Rcpp'
##
## Nothing else in the package pulls Rcpp in, and no other test reaches the
## compiled code, so these are the only guards against that regression.

test_that("IC based methods can be called", {
    expect_true("Rcpp" %in% loadedNamespaces())

    hsGO <- godata(annoDb = "org.Hs.eg.db", ont = "BP", computeIC = TRUE)

    for (m in c("Resnik", "Lin", "Jiang", "Rel")) {
        x <- goSim("GO:0006954", "GO:0006952", semData = hsGO, measure = m)
        expect_type(x, "double")
        expect_length(x, 1)
        expect_false(is.na(x))
        expect_true(is.finite(x))
    }
})

test_that("IC based methods return a full term-by-term matrix", {
    hsGO <- godata(annoDb = "org.Hs.eg.db", ont = "BP", computeIC = TRUE)
    go <- c("GO:0006954", "GO:0006952", "GO:0006412")

    for (m in c("Resnik", "Lin", "Jiang", "Rel")) {
        mat <- termSim(go, go, hsGO, method = m)
        expect_equal(dim(mat), c(3L, 3L))
        expect_false(any(is.na(mat[upper.tri(mat)])))
    }
})

test_that("IC based methods work for the other ontologies", {
    for (ont in c("MF", "CC")) {
        hsGO <- godata(annoDb = "org.Hs.eg.db", ont = ont, computeIC = TRUE)
        go <- head(names(hsGO@IC), 3)
        expect_no_error(termSim(go, go, hsGO, method = "Lin"))
    }
})

test_that("every annotated term gets an IC", {
    ## computeIC() used to take its term universe from the `gotbl` table shipped
    ## in data/, which was last rebuilt in 2021. Any term GO.db added since then
    ## was given no IC at all, so goSim()/geneSim() returned NA for it even
    ## though its descendants carry annotations and its IC is computable (issue
    ## #33). The universe now comes from the installed GO.db, so a term that is
    ## actually annotated must always be scorable.
    for (ont in c("BP", "CC", "MF")) {
        hsGO <- godata(annoDb = "org.Hs.eg.db", ont = ont, computeIC = TRUE)
        annotated <- unique(hsGO@geneAnno$GO)

        expect_gt(length(annotated), 1000)
        expect_true(all(annotated %in% names(hsGO@IC)))
        expect_false(any(is.na(hsGO@IC[annotated])))
        expect_true(all(is.finite(hsGO@IC[annotated])))
    }
})
